#!/bin/bash

# Define a function to calculate factorial recursively
factorial() {
    if [ $1 -eq 0 ]; then
        echo 1
    else
        local prev=$(factorial $(($1 - 1)))
        echo $(($1 * $prev))
    fi
}

# Read input from user
echo -n "Enter a number: "
read num

# Call the factorial function with the input number
result=$(factorial $num)

# Print the result
echo "Factorial of $num is: $result"
